/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ChampionsIndexImport } from './routes/champions/index'
import { Route as ChampionsChampionIdImport } from './routes/champions/$championId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChampionsIndexRoute = ChampionsIndexImport.update({
  id: '/champions/',
  path: '/champions/',
  getParentRoute: () => rootRoute,
} as any)

const ChampionsChampionIdRoute = ChampionsChampionIdImport.update({
  id: '/champions/$championId',
  path: '/champions/$championId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/champions/$championId': {
      id: '/champions/$championId'
      path: '/champions/$championId'
      fullPath: '/champions/$championId'
      preLoaderRoute: typeof ChampionsChampionIdImport
      parentRoute: typeof rootRoute
    }
    '/champions/': {
      id: '/champions/'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/champions/$championId': typeof ChampionsChampionIdRoute
  '/champions': typeof ChampionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/champions/$championId': typeof ChampionsChampionIdRoute
  '/champions': typeof ChampionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/champions/$championId': typeof ChampionsChampionIdRoute
  '/champions/': typeof ChampionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/champions/$championId' | '/champions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/champions/$championId' | '/champions'
  id: '__root__' | '/' | '/champions/$championId' | '/champions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChampionsChampionIdRoute: typeof ChampionsChampionIdRoute
  ChampionsIndexRoute: typeof ChampionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChampionsChampionIdRoute: ChampionsChampionIdRoute,
  ChampionsIndexRoute: ChampionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/champions/$championId",
        "/champions/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/champions/$championId": {
      "filePath": "champions/$championId.tsx"
    },
    "/champions/": {
      "filePath": "champions/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
